export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import './globals.css'
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href="./favicon.ico"/>
      <body>{children}</body>
    </html>
  )
}
